### ISSUE TITLE
Function IFERROR not found

### ISSUE THREAD

**Issue by amitm02** [fabiooshiro/xlsx-calc#10]
If the sheet contains IFERROR function, xlsx-calc crashes with:

```
Function IFERROR not found
    at exec_formula (/Users/amitm02/xlsxNode/node_modules/xlsx-calc/xlsx-calc.js:831:17)
    at mymodule (/Users/amitm02/xlsxNode/node_modules/xlsx-calc/xlsx-calc.js:440:7)
```

**Comment by fabiooshiro** [comment]
plz try the new version 0.4.1

fell free to reopen if IFERROR doesnt works as expected,
but if you got another missing formula open another issue.
