### ISSUE TITLE
Can't Handle Structured References

### ISSUE THREAD

**Issue by Kyle1297** [fabiooshiro/xlsx-calc#102]
It doesn't seem like `xlsx-calc` can handle [structured references](https://support.microsoft.com/en-us/office/using-structured-references-with-excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e) yet. 

See some of the errors that I am getting when the `exec/check_variable` function is ran (in the Exp.js file):

```
[Exp.js] - H32: evaluating TRANSPOSE(_xlws.SORT(TRIM(UNIQUE(_xlws.FILTER(DataTable1[Product],(DataTable1[Product]<>"")*(DataTable1[Manufacturer]=F32))))))
Undefined DataTable1[Product]
[Exp.js] - H32: evaluating TRANSPOSE(_xlws.SORT(TRIM(UNIQUE(_xlws.FILTER(DataTable1[Product],(DataTable1[Product]<>"")*(DataTable1[Manufacturer]=F32))))))
Undefined DataTable1[Product]
[Exp.js] - C42: evaluating IFERROR(IF(VLOOKUP(INDEX(Table3[Supplier],MATCH('10. Data Stuff - Hidden'!B42,Table3[Composition],0)),$F$3:$G$32,2,FALSE)>0,OFFSET($F$3,MATCH('1. CarbonFootprint- User Fields'!C32,$F$3:$F$32,0)-1,2,1,VLOOKUP('1. CarbonFootprint- User Fields'!C32,$F$3:$G$32,2,FALSE)),""),"")
Undefined DataTable1[Product]
[Exp.js] - H32: evaluating TRANSPOSE(_xlws.SORT(TRIM(UNIQUE(_xlws.FILTER(DataTable1[Product],(DataTable1[Product]<>"")*(DataTable1[Manufacturer]=F32))))))
Undefined DataTable1[Product]
[Exp.js] - H32: evaluating TRANSPOSE(_xlws.SORT(TRIM(UNIQUE(_xlws.FILTER(DataTable1[Product],(DataTable1[Product]<>"")*(DataTable1[Manufacturer]=F32))))))
Undefined DataTable1[Product]
/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/index.js:16
          throw error
          ^

Error: Undefined DataTable1[Product]
    at checkVariable (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:64:19)
    at exec (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:81:25)
    at Exp.self.calc (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:171:9)
    at exec (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:84:45)
    at Exp.self.calc (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:147:9)
    at /Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/UserFnExecutor.js:19:67
    at Array.map (<anonymous>)
    at UserFnExecutor.self.calc (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/UserFnExecutor.js:19:58)
    at Exp.self.calc (/Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/Exp.js:200:32)
    at /Users/kylegriffin/Documents/kyle/grounded/vulcan/sustainability/node_modules/xlsx-calc/src/UserFnExecutor.js:19:67
```

**Comment by Kyle1297** [comment]
@fabiooshiro

**Comment by Kyle1297** [comment]
Oh this might be related to this issue: https://github.com/fabiooshiro/xlsx-calc/issues/88

**Comment by fabiooshiro** [comment]
Could you send a json example with the DataTable?
