### ISSUE TITLE
Cannot read property 'f' of undefined

### ISSUE THREAD

**Issue by usmanshb** [fabiooshiro/xlsx-calc#18]
code breaks if some cell is undefined.

`TypeError: Cannot read property 'f' of undefined
    at find_all_cells_with_formulas (f:\projects\upgraded\platalyticsfrontend\node_modules\xlsx-calc\lib\xlsx-calc.js:825:34)
    at mymodule (f:\projects\upgraded\platalyticsfrontend\node_modules\xlsx-calc\lib\xlsx-calc.js:1554:20)
    at test (f:\projects\upgraded\platalyticsfrontend\controllers\dataWranglerController.js:163:9)
    at Layer.handle [as handle_request] (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\layer.js:95:5)
    at f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:335:12)
    at next (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:174:3)
    at router (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:317:13)
    at f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (f:\projects\upgraded\platalyticsfrontend\node_modules\express\lib\router\index.js:335:12)`

**Comment by fabiooshiro** [comment]
plz try new version 0.5.7

**Comment by fabiooshiro** [comment]
by the way, how could it be undefined?
