### ISSUE TITLE
Defined Name Issue

### ISSUE THREAD

**Issue by capndave** [fabiooshiro/xlsx-calc#20]
Hi. I'm not sure if this is a problem with xlsx-calc or with xlsx library but I'm not able to handle defined names for cells or ranges. 

```
const xlsx = require('xlsx')
const xlsx_calc = require('xlsx-calc')
const formulajs = require('formulajs')

xlsx_calc.import_functions(formulajs)

const workbook = xlsx.readFile('filename')

const calcd = xlsx_calc(workbook)

```

 throws an error,

```
{"error":{},"level":"error","message":"uncaughtException: Undefined NBHDJ\nError: Undefined NBHDJ\n    at checkVariable (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:228:19)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:236:21)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:302:9)\n    at exec_minus (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:254:38)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:268:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:281:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:278:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)","stack":"Error: Undefined NBHDJ\n    at checkVariable (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:228:19)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:236:21)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:302:9)\n    at exec_minus (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:254:38)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:268:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:281:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)\n    at Exp.self.calc (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:278:9)\n    at exec (/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js:238:44)","exception":true,"date":"Tue Jan 29 2019 16:36:27 GMT-0600 (Central Standard Time)","process":{"pid":12726,"uid":1000,"gid":1000,"cwd":"/home/administrator/Documents/equity-grids-2019","execPath":"/usr/local/n/versions/node/11.4.0/bin/node","version":"v11.4.0","argv":["/usr/local/n/versions/node/11.4.0/bin/node","/home/administrator/Documents/equity-grids-2019/app.js"],"memoryUsage":{"rss":196091904,"heapTotal":124727296,"heapUsed":101315992,"external":25369145}},"os":{"loadavg":[2.5673828125,2.44921875,2.46728515625],"uptime":348172},"trace":[{"column":19,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"checkVariable","line":228,"method":null,"native":false},{"column":21,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"exec","line":236,"method":null,"native":false},{"column":9,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"Exp.self.calc","line":302,"method":"calc","native":false},{"column":38,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"exec_minus","line":254,"method":null,"native":false},{"column":9,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"Exp.self.calc","line":268,"method":"calc","native":false},{"column":44,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"exec","line":238,"method":null,"native":false},{"column":9,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"Exp.self.calc","line":281,"method":"calc","native":false},{"column":44,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"exec","line":238,"method":null,"native":false},{"column":9,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"Exp.self.calc","line":278,"method":"calc","native":false},{"column":44,"file":"/home/administrator/Documents/equity-grids-2019/node_modules/xlsx-calc/lib/xlsx-calc.js","function":"exec","line":238,"method":null,"native":false}]}
```

**Comment by fabiooshiro** [comment]
Hi

Do you know where I can find the values of names in the json workbook?

**Comment by fabiooshiro** [comment]
Please run this:
```console.log(workbook.Workbook.Names)```
and send me the results.

I wrote some file to seek that information...
![image](https://user-images.githubusercontent.com/218768/52052437-87051200-253d-11e9-8af9-96aaeb37e482.png)

**Comment by capndave** [comment]
Sure, the results are:
''''[ { Name: 'ACRES', Ref: '[1]Sheet2!$L$2:$L$5000' },
  { Name: 'CLASSL', Ref: '[1]Sheet2!$H$2:$H$5000' },
  { Name: 'CLASSN', Ref: '[1]Sheet2!$I$2:$I$5000' },
  { Name: 'CONDJ', Ref: 'data!$X$4:$X$10000' },
  { Name: 'DATA', Ref: '[1]Sheet2!$A$1:$W$5000' },
  { Name: 'DATAJ', Ref: 'data!$A$4:$AH$10000' },
  { Name: 'ECOOBJ', Ref: 'data!$Z$4:$Z$10000' },
  { Name: 'Ef_Year', Ref: '[1]Sheet2!$D$2:$D$5000' },
  { Name: 'EFFBLTJ', Ref: 'data!$F$4:$F$10000' },
  { Name: 'ExternalData_1', Sheet: 0, Ref: 'data!$A$3:$AG$7055' },
  { Name: 'FINOUTJ', Ref: 'data!$AC$4:$AC$10000' },
  { Name: 'FOOTPRINTJ', Ref: 'data!$AF$4:$AF$10000' },
  { Name: 'FUNOBJ', Ref: 'data!$AA$4:$AA$10000' },
  { Name: 'IMPCJ', Ref: 'data!$L$4:$L$10000' },
  { Name: 'IMPPPSF', Ref: '[1]Sheet2!$J$2:$J$5000' },
  { Name: 'IMPPPSFJ', Ref: 'data!$O$4:$O$10000' },
  { Name: 'IMPSJ', Ref: 'data!$M$4:$M$10000' },
  { Name: 'IMPVALJ', Ref: 'data!$N$4:$N$10000' },
  { Name: 'LANDPSF', Ref: '[1]Sheet2!$K$2:$K$5000' },
  { Name: 'LANDSFJ', Ref: 'data!$AD$4:$AD$10000' },
  { Name: 'LANDVALJ', Ref: 'data!$W$4:$W$10000' },
  { Name: 'LIV_AREA', Ref: '[1]Sheet2!$E$2:$E$5000' },
  { Name: 'LIVAREAJ', Ref: 'data!$H$4:$H$10000' },
  { Name: 'MADJJ', Ref: 'data!$D$4:$D$10000' },
  { Name: 'MAINUNITJ', Ref: 'data!$S$4:$S$10000' },
  { Name: 'MARKETJ', Ref: 'data!$I$4:$I$10000' },
  { Name: 'MAXUNITJ', Ref: 'data!$T$4:$T$10000' },
  { Name: 'MIXCOUNT', Ref: 'data!$AE$4:$AE$10000' },
  { Name: 'NBHD', Ref: '[1]Sheet2!$B$2:$B$5000' },
  { Name: 'NBHDJ', Ref: 'data!$B$4:$B$10000' },
  { Name: 'PGJ', Ref: 'data!$AB$4:$AB$10000' },
  { Name: 'PHYOBJ', Ref: 'data!$Y$4:$Y$10000' },
  { Name: 'PIDJ', Ref: 'data!$A$4:$A$10000' },
  { Name: 'PPSF', Ref: '[1]Sheet2!$G$2:$G$5000' },
  { Name: 'PPSFJ', Ref: 'data!$K$4:$K$10000' },
  { Name: 'PPSFLANDJ', Ref: 'data!$U$4:$U$10000' },
  { Name: 'PROTEST', Ref: 'data!$AG$4:$AG$10000' },
  { Name: 'RCNLDADNTLJ', Ref: 'data!$R$4:$R$10000' },
  { Name: 'RCNLDPPSFJ', Ref: 'data!$Q$4:$Q$10000' },
  { Name: 'SITUSJ', Ref: 'data!$E$4:$E$10000' },
  { Name: 'STREETJ', Ref: 'data!$C$4:$C$10000' },
  { Name: 'TOTALRNCLDJ', Ref: 'data!$P$4:$P$10000' },
  { Name: 'UNITLANDJ', Ref: 'data!$V$4:$V$10000' },
  { Name: 'YRBLTJ', Ref: 'data!$G$4:$G$10000' } ]
''''

**Comment by fabiooshiro** [comment]
'[1]Sheet2' name is weird...

**Comment by fabiooshiro** [comment]
try the new version xlsx-calc@0.5.9 with 
```
let calculator = XLSX_CALC.calculator(workbook);
calculator.execute();
```
