### ISSUE TITLE
IF condition get transformed into TRUE, and fails

### ISSUE THREAD

**Issue by olivierchatry** [fabiooshiro/xlsx-calc#25]
Some oddity, 

I have a cell with a formula : `=IF(L4=1,L464,0)`
L4 is a Number cell, with this formula : `=$Inputs.N4<>""`

When using the library, 
`=IF(L4=1,L464,0)` get transformed ( from the debugger ) to `=IF(L4=TRUE,L464,0)`
And the library assert with `Error: Undefined TRUE` with this callstack :

```
Error: Undefined TRUE
    at checkVariable (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:268:19)
    at exec (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:282:25)
    at Exp.self.calc (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:367:9)
    at UserRawFnExecutor._if (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:1018:19)
    at UserRawFnExecutor.self.calc (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:657:30)
    at Exp.self.calc (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:381:32)
    at Exp.update_cell_value (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:230:35)
    at exec_formula (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:763:14)
    at mymodule (/home/olivier/Downloads/test/node_modules/xlsx-calc/lib/xlsx-calc.js:1747:9)
    at Object.<anonymous> (/home/olivier/Downloads/test/index.js:15:1)
```
I have tried to reproduce this in a simple sheet, but was not able to. Still investigating.

**Comment by olivierchatry** [comment]
Seems like the formula with "TRUE" inside directly come from the parser. It seems like TRUE is not a valid value in the parser, and just passed as a string instead of a RawValue.

I'm still not sure why excel save my formula `=1` with `=TRUE` ( I checked L4, and it is a numerical ).

**Comment by fabiooshiro** [comment]
I wrote a test:

`test/2-bug-fix-test.js`
```js
    it('should understand TRUE', function() {
        workbook.Sheets.Sheet1.A1.f = '=IF(L4=TRUE,L464,0)';
        workbook.Sheets.Sheet1.L464 = { v: 24 };
        workbook.Sheets.Sheet1.L4 = { v: 1 };
        XLSX_CALC(workbook);
        assert.equal(workbook.Sheets.Sheet1.A1.v, 24);
    });
```
changed the `src/str_2_val.js`

I think thats ok now...

**Comment by olivierchatry** [comment]
Thanks a lot ! Seems to work.
