### ISSUE TITLE
Cannot read property 'calc' of undefined

### ISSUE THREAD

**Issue by lukas1994** [fabiooshiro/xlsx-calc#39]
I'm getting
```
TypeError: Cannot read property 'calc' of undefined
    at UserRawFnExecutor._if (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:1023:22)
    at UserRawFnExecutor.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:662:30)
    at Exp.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:386:32)
    at Exp.update_cell_value (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:229:35)
    at Object.exec_formula (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:752:14)
    at RefValue.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:565:25)
    at exec_minus (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:299:37)
    at Exp.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:323:9)
    at Exp.update_cell_value (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:229:35)
    at Object.exec_formula (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:752:14)
```

This is my code:
```
var XLSX = require('xlsx');
var XLSX_CALC = require('xlsx-calc');
var formulajs = require('formulajs');

// import your calc functions lib
XLSX_CALC.import_functions(formulajs);

var workbook = XLSX.readFile('fund.xlsx');

function f() {
  workbook.Sheets['Fund Economics'].C8.v = 30000;
  // recalc the workbook
  XLSX_CALC(workbook);
  return workbook.Sheets['Fund Economics'].W39
}
console.log(workbook.Sheets['Fund Economics'].C8)
console.log(f())
```

I attached my spreadsheet.

[fund.xlsx](https://github.com/fabiooshiro/xlsx-calc/files/3424340/fund.xlsx)

**Comment by fabiooshiro** [comment]
Dear Friend,

I think your spreadsheet is too large, see the image below.

![Screenshot from 2019-07-24 23-09-01](https://user-images.githubusercontent.com/218768/61840593-1560ad80-ae68-11e9-871f-1203ac4c2d49.png)

Anyway, maybe some of your IFs refers to an inexisting cell

**Comment by lukas1994** [comment]
the spreadsheet works in Excel and it has less than 10k non empty cells
where did you get this error message?

**Comment by fabiooshiro** [comment]
I got this message from LibreOffice

**Comment by fabiooshiro** [comment]
The problem cell is D41
working on it

**Comment by fabiooshiro** [comment]
@lukas1994 try the new version 0.6.1 plz

**Comment by lukas1994** [comment]
Thanks a lot, Fabio!
Now I'm getting another error however :/

```
TypeError: row[i].toLowerCase is not a function
    at UserFnExecutor.hlookup (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:1370:55)
    at UserFnExecutor.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:641:36)
    at exec_minus (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:299:37)
    at Exp.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:323:9)
    at UserRawFnExecutor._if (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:1047:22)
    at UserRawFnExecutor.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:682:34)
    at Exp.self.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:386:32)
    at Exp.update_cell_value (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:229:35)
    at Object.exec_formula (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:779:14)
    at Range.calc (/Users/lukaskoebis/js_excel/node_modules/xlsx-calc/lib/xlsx-calc.js:475:33)
```

Are you aware of any mode stable libraries to evaluate Excel files? Doesn't need to be JS. Python or any other language should work too.
I've tried a few so far and none could successfully evaluate my file.

**Comment by fabiooshiro** [comment]
Hi @lukas1994 
Keep Calm and Carry On
I will see that

**Comment by fabiooshiro** [comment]
@lukas1994 try the 0.6.2

Your file has some cells with "#VALUE!" maybe that cause some problems...

**Comment by fabiooshiro** [comment]
Can I commit your file for my integration tests?

**Comment by fabiooshiro** [comment]
> Are you aware of any mode stable libraries to evaluate Excel files? Doesn't need to be JS. Python or any other language should work too.

I'm not. This project was started when me and my partners applied tests on some intern candidates. The test was a TDD aproach to create a calculator to do some string math evaluations without regex and of course not "eval" functions. The aim of this project is to see what happens if each partner do the test.

**Comment by fabiooshiro** [comment]
Pay attention to the type of cell.
When cell.t == 'e' it's mean an error and the cell.v is a error number.

**Comment by fabiooshiro** [comment]
@lukas1994 closing for now, feel free to open a new issue or reopen this one.

Thx
