### ISSUE TITLE
Formulas with references to other quoted sheets cannot calculate

### ISSUE THREAD

**Issue by dejarp** [fabiooshiro/xlsx-calc#6]
Example ```='Workbook@Sheet'!A1```

code currently splits on ! but does not account for single quotes before the ! and therefore looks for a sheet called ```'Workbook@Sheet'``` which does not exist.

**Comment by fabiooshiro** [comment]
Give me a star and an example file plz ;-)

**Comment by Loilo** [comment]
### The simplest case:

* Two sheets, named `A` and `B C`
* Cell `A1` in `A` references cell `A1` in `B C`
* Space in name of `B C` forces reference to quote sheet name:

  ```
  'B C'!A1
  ```

### File
The scenario as a file: [abc.xlsx](https://github.com/fabiooshiro/xlsx-calc/files/1179820/abc.xlsx)

### Code
JavaScript source code to reproduce:

```javascript
const XLSX = require('xlsx')
const XLSX_CALC = require('xlsx-calc')

const workbook = XLSX.readFile('abc.xlsx')

workbook.Sheets['B C'].A1.v = 2000

XLSX_CALC(workbook)
```

### Stack trace
```
.../node_modules/xlsx-calc/xlsx-calc.js:806
        throw e;
        ^

TypeError: Cannot read property 'A1' of undefined
    at RefValue.calc (.../node_modules/xlsx-calc/xlsx-calc.js:472:27)
    at Exp.self.calc (.../node_modules/xlsx-calc/xlsx-calc.js:650:31)
    at exec_formula (.../node_modules/xlsx-calc/xlsx-calc.js:792:33)
    at mymodule (.../node_modules/xlsx-calc/xlsx-calc.js:406:7)
    at Object.<anonymous> (/Users/flrl/Sites/fiddle/www/modules/biotark/calc.js:16:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by fabiooshiro** [comment]
Have a nice weekend!

The bug has gone...

Thx @Loilo and @dejarp
