### ISSUE TITLE
Undefined Variable Error

### ISSUE THREAD

**Issue by dimitristaufer** [fabiooshiro/xlsx-calc#67]
Hi, I am using this code snippet to test the re-calculation of my workbook. I am, however, getting an "Undefined Variable" error.
Is there any chance you could have a quick look at my XLSX file? Thanks in advance.

```js
var XLSX = require('xlsx');
var XLSX_CALC = require('xlsx-calc');
var workbook = XLSX.readFile('./sample.xlsx');
XLSX_CALC(workbook);
console.log(workbook.Sheets['Kalkulator_1'].C29);`
```

```
/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:51
                throw e;
                ^

Error: Undefined Verpackungsspielraum
    at checkVariable (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:64:19)
    at exec (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:78:25)
    at Exp.self.calc (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:133:9)
    at Exp.update_cell_value (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:26:35)
    at Object.exec_formula (/var/www/excel_experiments/node_modules/xlsx-calc/src/exec_formula.js:52:14)
    at RefValue.calc (/var/www/excel_experiments/node_modules/xlsx-calc/src/RefValue.js:48:25)
    at exec (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:79:48)
    at Exp.self.calc (/var/www/excel_experiments/node_modules/xlsx-calc/src/Exp.js:148:9)
    at UserRawFnExecutor._if (/var/www/excel_experiments/node_modules/xlsx-calc/src/formulas-raw.js:45:19)
    at UserRawFnExecutor.self.calc (/var/www/excel_experiments/node_modules/xlsx-calc/src/UserRawFnExecutor.js:9:34)
```

**Comment by fabiooshiro** [comment]
Try this -> https://github.com/fabiooshiro/xlsx-calc/blob/master/test/4-super-var.tests.js

**Comment by fabiooshiro** [comment]
I will close this issue, feel free to reopen it.
