### ISSUE TITLE
Error: Undefined when using references in formated tables

### ISSUE THREAD

**Issue by snibbo** [fabiooshiro/xlsx-calc#88]
Hi, 

thank you so much for your effort you put into this project!!

First time, I am opening an issue, so I hope to do it correctly. 

My script errors when I use references within a formated table, eg. my table is named "tblParameters" and one column has the name "Expected Value". When I use a formula like "=[@[Expected Value]]* (1 + 0,1)" in another cell, I receive an error.
Indeed, the cell is empty, but when I replace the formulas with the "usual" cell format (eg. "=E125 * (1 + 0,1)", there is no error.

Error: Undefined tblParameters[[#ThisRow],[ExpectedValue
    at checkVariable (...\node_modules\xlsx-calc\src\Exp.js:64:19)
    at exec (...\node_modules\xlsx-calc\src\Exp.js:77:25)
    at Exp.self.calc (...\node_modules\xlsx-calc\src\Exp.js:133:9)
    at Exp.update_cell_value (...\node_modules\xlsx-calc\src\Exp.js:26:35)
    at exec_formula (...\node_modules\xlsx-calc\src\exec_formula.js:52:14)
    at mymodule (...\node_modules\xlsx-calc\src\index.js:12:9)
    at Object.<anonymous> (...\app.js:126:1)

Is that a known issue? If you need any other information, please let me know - happy to support!

Thanks!
snibbo

**Comment by fabiooshiro** [comment]
I really have no idea...
Could you send a sample file?

**Comment by snibbo** [comment]
Sorry, seems that I have missed your comment. Please find a file attached. This one is using a formatted table.

Min and Max column are referencing to column "Expected Value", but xlsx-calc is not able to parse that: 
error executing formula sheet Tabelle1 cell D2 Error: Undefined tblParameters[[#ThisRow],[ExpectedValue]]

In my project I have removed to formatted table again, so it is working, but would be nice if this is supported.

```
async function myMain() {
  let workbook = XLSX.readFile('FormatedTable.xlsx');
  // Recalc the workbook
  XLSX_CALC(workbook, { continue_after_error: true, log_error: true });
}
myMain();
```

[FormatedTable.xlsx](https://github.com/fabiooshiro/xlsx-calc/files/14296539/FormatedTable.xlsx)
