### ISSUE TITLE
Function DEGREES not found

### ISSUE THREAD

**Issue by nhanquach** [fabiooshiro/xlsx-calc#94]
Hi everyone,
Thank you for the amazing work. I tried to use this lib but I ran into this issue.
As the name suggested, function [DEGREES](https://support.microsoft.com/en-us/office/degrees-function-4d6ec4db-e694-4b94-ace0-1cc3f61f9ba1) is not found for some reason. I tried use xlsx-calc with formatjs as well, but nothing change.

Thank you.

FYI: logs:
```
/node_modules/xlsx-calc/src/expression_builder.js:68
            throw new Error('"' + formula.sheet_name + '"!' + formula.name + ': Function ' + buffer + ' not found');
                  ^
Error: "Sheet1"!H12: Function DEGREES not found
    at ini_parentheses (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/expression_builder.js:68:19)
    at start (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/expression_builder.js:112:13)
    at expression_builder (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/expression_builder.js:131:9)
    at build_expression (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/exec_formula.js:47:12)
    at Object.exec_formula (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/exec_formula.js:51:20)
    at RefValue.calc (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/RefValue.js:48:25)
    at exec (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/Exp.js:84:45)
    at Exp.self.calc (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/Exp.js:159:9)
    at UserRawFnExecutor._if (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/formulas-raw.js:45:19)
    at UserRawFnExecutor.self.calc (/Users/username/side-projects/online-color-convert/node_modules/xlsx-calc/src/UserRawFnExecutor.js:9:34)
```

**Comment by nhanquach** [comment]
I was my fault, I import the `formatjs` incorrectly!.
